
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/chenguangwei/.antigravity/antigravity/bin/"
      - "/Users/chenguangwei/.local/bin/"
      - "/Users/chenguangwei/.bun/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/chenguangwei/.nvm/versions/node/v23.5.0/bin/"
      - "/opt/anaconda3/condabin/"
      - "/Users/chenguangwei/.rbenv/shims/"
      - "/Users/chenguangwei/.rbenv/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/chenguangwei/.orbstack/bin/"
      - "/Users/chenguangwei/.rvm/bin/"
    searched_directories:
      - "/Users/chenguangwei/.antigravity/antigravity/bin/uname"
      - "/Users/chenguangwei/.local/bin/uname"
      - "/Users/chenguangwei/.bun/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Users/chenguangwei/.nvm/versions/node/v23.5.0/bin/uname"
      - "/opt/anaconda3/condabin/uname"
      - "/Users/chenguangwei/.rbenv/shims/uname"
      - "/Users/chenguangwei/.rbenv/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/chenguangwei/.antigravity/antigravity/bin"
        - "/Users/chenguangwei/.local/bin"
        - "/Users/chenguangwei/.bun/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/chenguangwei/.nvm/versions/node/v23.5.0/bin"
        - "/opt/anaconda3/condabin"
        - "/Users/chenguangwei/.rbenv/shims"
        - "/Users/chenguangwei/.rbenv/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/chenguangwei/.orbstack/bin"
        - "/Users/chenguangwei/.rvm/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/chenguangwei/.antigravity/antigravity/bin/"
      - "/Users/chenguangwei/.local/bin/"
      - "/Users/chenguangwei/.bun/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/chenguangwei/.nvm/versions/node/v23.5.0/bin/"
      - "/opt/anaconda3/condabin/"
      - "/Users/chenguangwei/.rbenv/shims/"
      - "/Users/chenguangwei/.rbenv/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/chenguangwei/.orbstack/bin/"
      - "/Users/chenguangwei/.rvm/bin/"
    searched_directories:
      - "/Users/chenguangwei/.antigravity/antigravity/bin/install_name_tool"
      - "/Users/chenguangwei/.local/bin/install_name_tool"
      - "/Users/chenguangwei/.bun/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/Users/chenguangwei/.nvm/versions/node/v23.5.0/bin/install_name_tool"
      - "/opt/anaconda3/condabin/install_name_tool"
      - "/Users/chenguangwei/.rbenv/shims/install_name_tool"
      - "/Users/chenguangwei/.rbenv/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/chenguangwei/.antigravity/antigravity/bin"
        - "/Users/chenguangwei/.local/bin"
        - "/Users/chenguangwei/.bun/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/chenguangwei/.nvm/versions/node/v23.5.0/bin"
        - "/opt/anaconda3/condabin"
        - "/Users/chenguangwei/.rbenv/shims"
        - "/Users/chenguangwei/.rbenv/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/chenguangwei/.orbstack/bin"
        - "/Users/chenguangwei/.rvm/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
